# These are supported funding model platforms

github: Monster2408
patreon: Monster2408
open_collective: Monster2408
ko_fi: Monster2408
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Monster2408
issuehunt: Monster2408
otechie: Monster2408
custom:
  - https://paypal.me/pools/c/8BuanO0eM2
